[workspace]
members = [
    "0_basics/src/lib",
    "0_basics",
    "1_concepts",
    "1_concepts/1_*",
    "2_idioms",
    "2_idioms/2_*",
    "3_ecosystem",
    "3_ecosystem/3_*",
    "4_backend",
    "4_backend/4_*",
]
